/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as IndexRouteImport } from './routes/index';
import { Route as LeadsLeadIdRouteImport } from './routes/leads/$leadId';
import { Route as LeadsIndexRouteImport } from './routes/leads/index';
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index';
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new';
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const LeadsIndexRoute = LeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => rootRouteImport,
});
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => rootRouteImport,
});
const CampaignsNewRoute = CampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => rootRouteImport,
});
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    DashboardRoute: DashboardRoute,
    LoginRoute: LoginRoute,
    CampaignsNewRoute: CampaignsNewRoute,
    CampaignsIndexRoute: CampaignsIndexRoute,
    LeadsIndexRoute: LeadsIndexRoute,
    LeadsLeadIdRoute: LeadsLeadIdRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
//# sourceMappingURL=routeTree.gen.js.map