// Placeholder route-tree generated file
// In production this is auto-generated by TanStack Router via vite plugin
// Run: pnpm --filter web dev  — it generates this file automatically
import { createRouteTree } from '@tanstack/react-router'

export const routeTree = createRouteTree()
